/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/TEST.glb 
Author: Alexis (https://sketchfab.com/alexis.eginard)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-stylised-building-from-a-cheryl-young-artwork-c73b38d110114466a2dd8de952d2924d
Title: 3d Stylised Building from a Cheryl Young artwork
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function TEST(props) {
  const { nodes, materials } = useGLTF('/TEST.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.0095}>
        <group position={[0, -25.066, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Edificio_Edificio_0.geometry} material={materials.Edificio} />
          <mesh geometry={nodes.Edificio_Outline_0.geometry} material={materials.Outline} />
        </group>
        <group position={[-33.417, 214.295, -44.825]} rotation={[-1.595, 0.024, -0.018]} scale={100}>
          <mesh geometry={nodes.Detalles_Detalles_0.geometry} material={materials.Detalles} />
          <mesh geometry={nodes.Detalles_Outline_0.geometry} material={materials.Outline} />
        </group>
        <group position={[-33.417, 214.295, -44.825]} rotation={[-1.595, 0.024, -0.018]} scale={100}>
          <mesh geometry={nodes.Detalles001_Detalles_0.geometry} material={materials.Detalles} />
          <mesh geometry={nodes.Detalles001_Outline_0.geometry} material={materials.Outline} />
        </group>
        <group position={[-33.417, 214.295, -44.825]} rotation={[-1.595, 0.024, -0.018]} scale={100}>
          <mesh geometry={nodes.Detalles002_Detalles_0.geometry} material={materials.Detalles} />
          <mesh geometry={nodes.Detalles002_Outline_0.geometry} material={materials.Outline} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/TEST.glb')
